<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\DefaultController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/DefaultController.php';

return $this->services['App\Controller\DefaultController'] = new \App\Controller\DefaultController();
