<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNz3Nii\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNz3Nii/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXNz3Nii.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXNz3Nii\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXNz3Nii\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XNz3Nii',
    'container.build_id' => '150a05bd',
    'container.build_time' => 1517405702,
));
